### ISSUE TITLE
Cannot use URN as graph name

### ISSUE THREAD

**Issue by jaw111** [jindrichmynarz/sparql-to-graphviz#1]
When I try to use a URN `urn:x-arq:UnionGraph` as the graph name, I get an error:

    Failed to validate "-g urn:x-arq:UnionGraph": The graph must be a valid absolute IRI.

**Comment by jindrichmynarz** [comment]
Thanks for the report. I've forgotten about URNs. I've changed the code to allow URNs as graph IDs.
